### ISSUE TITLE
"Login failed, it appears you are offline." on first startup when logging in

### ISSUE THREAD

**Issue by mydoghasfleas** [ActiveState/OpenKomodoIDE#17]
I just installed Komodo and on first startup, it requires me to log in.

When entering my user and password, I get the message shown below ("Login failed, it appears you are offline.").

![image](https://github.com/ActiveState/OpenKomodoIDE/assets/125179869/76080930-510f-4660-b821-3fbeb7ebc220)

The log under `C:\Users\<user>\AppData\Local\ActiveState\KomodoIDE\12.0\pystderr.log` shows:

```
The certificate is not trusted because the issuer certificate is unknown.
```

I am behind a corporate firewall & proxy with a corporate root CA certificate.

I am including pystderr.log here (with sensitive information stripped out):

[pystderr.log](https://github.com/ActiveState/OpenKomodoIDE/files/12462727/pystderr.log)

**Comment by th3coop** [comment]
Closing in favour of https://github.com/ActiveState/OpenKomodoIDE/issues/4
